# Generated by Django 6.0.3 on 2026-03-05 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='自治体名')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='自治体コード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '自治体',
                'verbose_name_plural': '自治体',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('detected_site', '疑義地点'), ('inspection', '現地確認'), ('case', '案件')], max_length=20, verbose_name='対象種別')),
                ('target_id', models.UUIDField(verbose_name='対象ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='ファイル')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元ファイル名')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='案件番号')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('status', models.CharField(choices=[('open', 'オープン'), ('under_review', 'レビュー中'), ('waiting_field_check', '現地確認待ち'), ('monitoring', '監視中'), ('action_in_progress', '対応中'), ('closed', 'クローズ')], default='open', max_length=30, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '緊急')], default='medium', max_length=20, verbose_name='優先度')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='morido.case')),
            ],
            options={
                'verbose_name': '案件コメント',
                'verbose_name_plural': '案件コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id_display', models.CharField(blank=True, max_length=30, unique=True, verbose_name='疑義地点ID（表示用）')),
                ('status', models.CharField(choices=[('new', '新規'), ('triaged', 'トリアージ済'), ('field_check_required', '現地確認要'), ('monitoring', '継続監視'), ('false_positive', '誤検知'), ('linked_to_case', '案件紐付け済'), ('closed', 'クローズ')], default='new', max_length=30, verbose_name='状態')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='住所/地名')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='地域（区等）')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='リスクスコア')),
                ('is_continuous', models.BooleanField(default=False, verbose_name='継続的検知')),
                ('recommended_action', models.CharField(blank=True, max_length=200, verbose_name='推奨アクション')),
                ('permit_match_status', models.CharField(choices=[('unmatched', '未照合'), ('matched', '一致'), ('mismatch', '不一致'), ('not_applicable', '対象外')], default='unmatched', max_length=20, verbose_name='許認可照合状態')),
                ('detected_at', models.DateTimeField(verbose_name='検知日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sites', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detected_sites', to='morido.municipality')),
            ],
            options={
                'verbose_name': '疑義地点',
                'verbose_name_plural': '疑義地点',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='cases', to='morido.detectedsite'),
        ),
        migrations.CreateModel(
            name='FieldInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspected_at', models.DateTimeField(verbose_name='実施日時')),
                ('result', models.CharField(choices=[('monitoring', '監視継続'), ('false_positive', '誤検知'), ('case_required', '案件化要'), ('re_check', '要再確認')], max_length=30, verbose_name='確認結果')),
                ('finding', models.TextField(blank=True, verbose_name='所見メモ')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='確認地点 緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='確認地点 経度')),
                ('next_check_date', models.DateField(blank=True, null=True, verbose_name='次回確認推奨日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='morido.detectedsite')),
            ],
            options={
                'verbose_name': '現地確認',
                'verbose_name_plural': '現地確認',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('import_observations', '観測取り込み'), ('score_sites', 'スコア計算'), ('match_permits', '許認可照合'), ('generate_report', 'レポート生成'), ('rebuild_cache', 'キャッシュ再構築')], max_length=30, verbose_name='ジョブ種別')),
                ('status', models.CharField(choices=[('queued', '待機中'), ('running', '実行中'), ('succeeded', '成功'), ('failed', '失敗'), ('retrying', '再試行中'), ('cancelled', 'キャンセル')], default='queued', max_length=20, verbose_name='状態')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ジョブ実行履歴',
                'verbose_name_plural': 'ジョブ実行履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='部署名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='morido.municipality')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='morido.municipality'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField(verbose_name='観測日時')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='データソース')),
                ('image_url', models.URLField(blank=True, verbose_name='観測画像URL')),
                ('diff_image_url', models.URLField(blank=True, verbose_name='差分画像URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='morido.detectedsite')),
            ],
            options={
                'verbose_name': '観測',
                'verbose_name_plural': '観測',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_number', models.CharField(blank=True, max_length=100, verbose_name='許可番号')),
                ('match_result', models.CharField(choices=[('unmatched', '未照合'), ('matched', '一致'), ('mismatch', '不一致'), ('not_applicable', '対象外')], max_length=20, verbose_name='照合結果')),
                ('memo', models.TextField(blank=True, verbose_name='照合メモ')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_matches', to='morido.detectedsite')),
            ],
            options={
                'verbose_name': '許認可照合',
                'verbose_name_plural': '許認可照合',
            },
        ),
        migrations.CreateModel(
            name='SiteScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score_override', models.FloatField(blank=True, null=True, verbose_name='リスクスコア上書き')),
                ('recommended_action', models.CharField(blank=True, max_length=200, verbose_name='推奨アクション')),
                ('judgment', models.CharField(max_length=100, verbose_name='判定')),
                ('reason', models.TextField(blank=True, verbose_name='判定理由')),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('screened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='morido.detectedsite')),
            ],
            options={
                'verbose_name': 'トリアージ',
                'verbose_name_plural': 'トリアージ',
                'ordering': ['-screened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', '閲覧者'), ('operator', '監視担当'), ('inspector', '現地確認担当'), ('manager', '管理者'), ('admin', 'システム管理者')], default='viewer', max_length=20, verbose_name='ロール')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='morido.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_change', 'ステータス変更'), ('assignee_change', '担当変更'), ('priority_change', '優先度変更'), ('screening_saved', 'トリアージ保存'), ('inspection_created', '現地確認登録'), ('inspection_updated', '現地確認更新'), ('attachment_added', '添付追加'), ('attachment_deleted', '添付削除'), ('comment_added', 'コメント追加'), ('case_created', '案件作成'), ('setting_changed', '設定変更')], max_length=30, verbose_name='イベント種別')),
                ('target_type', models.CharField(max_length=30, verbose_name='対象種別')),
                ('target_id', models.UUIDField(verbose_name='対象ID')),
                ('before_value', models.JSONField(blank=True, null=True, verbose_name='変更前')),
                ('after_value', models.JSONField(blank=True, null=True, verbose_name='変更後')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-acted_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='morido_audi_target__bde09f_idx'), models.Index(fields=['event_type'], name='morido_audi_event_t_dd1f94_idx'), models.Index(fields=['acted_at'], name='morido_audi_acted_a_de194d_idx')],
            },
        ),
    ]
